issues:
  exclude-rules:
    # Disable some linters in tests.
    - path: _test\.go
      linters:
        - funlen
        - maligned
        - gomnd
    - path: adapter/internal/adaptertest
      linters:
        - funlen
        - maligned
        - gomnd

linters:
  enable:
    - testpackage
    - exportloopref
  disable:
    - paralleltest
    - gofumpt
    - exhaustivestruct
    - scopelint
    - gochecknoinits
    - gochecknoglobals
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused